- hosts: all
  become: yes
  tasks:
    - name: Download coolify install script
      shell: "wget -q https://get.coollabs.io/coolify/install.sh -O install.sh"
    - name: Executing coolify install script
      shell: "bash ./install.sh --do-not-track=1 --force"
